Providing a way to use typed objects as arguments
ChrisBuilds/terminaltexteffects pull request #5
Opened 2024-03-14 13:57 UTC by Navid-Means-Promise

As we discussed about in this [issue](https://github.com/ChrisBuilds/terminaltexteffects/issues/4), in the current PR I provided a file named "argsdataclass.py" that contains two important classes `ArgsDataClass` and `ArgField`.
Also I created a directory named "examples" that suppose to contain examples of using TTE in codes but temporarily it contains two files to demonestrate how to use typed args using `ArgsDataClass`

- The code is formatted and lint checked using ruff 
- This PR don't touch the current functionality of the project and as you asked in the [issue](https://github.com/ChrisBuilds/terminaltexteffects/issues/4)  I leaved the process of refactoring effects to use typed args, to you. although I can help on that if you want.
- I defined `TerminalArgs` class in terminal.py and this typed arg class is used in new approach but as I said It will not touch current functionality.
- It maybe subject to another discussion but as I saw `animation_rate` arg is a common arg between effects so instead of defining it in any effect separately it can be good to put it in the `TerminalArgs`  (as I did) or if you think it's not conceptually related to the terminal class we can define a base arg class to all effects arg classes inherit from.

2024-03-15 02:37 UTC, ChrisBuilds requested changes
Can you update this to pass mypy? There are a bunch of alerts, some of which go beyond simple modifications to type hints. At this time, mypy returns 0 issues across the entire project. 

At first glance, it looks like ArgFields are going to need to be cast to the type of the argument, and arg_class_metadata will need to be defined somewhere in the ArgsDataClass spec.

2024-03-16 00:17 UTC, Navid-Means-Promise commented
Sorry for that you told me before about mypy. now the code do pass it in the last commit.
About `ArgField` class I must say it is extended from python internal `Field` class defined in `dataclass` module and it meant to be assigned to a field . it's mentioned in [pep 0557](https://peps.python.org/pep-0557/#field-objects)
Also there is a helper function named `field` in the same module that will create and return an instance of `Field` class.
Mypy do accept assigning the result of `field` function to a field but not directly assigning new instance of `Field` class or any class extended from it.
[As there was a bug in mypy for dealing even with `field` function until Feb 2023 ](https://github.com/python/mypy/issues/11923) and due to my further research I convinced raising alerts about assigning in this case, is not correct; so I dealt the problem using  `# type: ignore[assignment]` at the end of field definitions.

2024-03-16 02:50 UTC, ChrisBuilds approved these changes

2024-03-16 02:50 UTC, ChrisBuilds approved these changes

2024-03-16 02:57 UTC, merged

2024-03-16 02:59 UTC, ChrisBuilds commented
Thanks. I'll poke around with the typing stuff and implement this functionality around the code base.